Deserialization of untrusted data
horde/imp pull request #7
Opened 2021-11-22 13:29 UTC by xgin

I want to resolve [ZDI-20-1051](https://www.zerodayinitiative.com/advisories/ZDI-20-1051/) vulnerability ([additional details](https://srcincite.io/blog/2020/08/19/a-smorgashorde-of-vulnerabilities-a-comparative-analysis-of-discovery.html#horde-groupware-webmail-edition-sort-sortpref-deserialization-of-untrusted-data-remote-code-execution-vulnerability)) using json serialization when possible and the list of allowed classes in other cases.

2021-11-22 21:12 UTC, xgin commented on lib/Compose.php
> +        if ($lang = @unserialize($prefs->getValue('reply_lang'), array('allowed_classes' => false))) {
I could not find a way to set a value of this preference. Is it used available anywhere?

2021-11-22 21:16 UTC, xgin commented on lib/LoginTasks/SystemTask/Upgrade.php
> +        $slist = @unserialize($prefs->getValue('stationery'), array('allowed_classes' => false));
Do you have a deprecation policy, when this property can be removed?

2022-01-12 20:32 UTC, yunosh commented on lib/Compose.php
> +        if ($lang = @unserialize($prefs->getValue('reply_lang'), array('allowed_classes' => false))) {
It's an advanced preference in the "Compose" preference group.

2022-01-12 20:35 UTC, yunosh commented on lib/LoginTasks/SystemTask/Upgrade.php
> +        $slist = @unserialize($prefs->getValue('stationery'), array('allowed_classes' => false));
It is already removed, as a settable preference. We don't remove migrations though.

2022-01-12 20:42 UTC, yunosh commented
The allowed_classes option is added with PHP 7.0, so we can only use this in IMP 7. For IMP 6, we need to find a different solution. Or at least do a version check.

2022-03-03 09:24 UTC, tribut requested changes
This patch appears to be broken as-is. See https://github.com/tribut/imp/pull/1/commits/2e27df51ceaf2f0326bd6217ff7480950ec830fc and https://github.com/tribut/imp/pull/1/commits/8a81c3b7027b5f5b961a2fcdc61cabc48cbdc54c

2022-03-03 09:24 UTC, tribut commented on lib/Factory/MailboxList.php
> +                    'IMP_Mailbox_List',
This appears to be missing `'IMP_Mailbox'`. In our tests, applying this patch without it broke viewing messages.

2022-03-03 16:36 UTC, tribut commented on lib/Flags.php
> +                'IMP_Flag_Imap_Seen',
This needs to include `'IMP_Flag_User'`.

2026-05-27 11:37 UTC, ralflang commented
## Related PRs for ZDI-20-1051 across the Horde ecosystem

The same unprotected `unserialize()` pattern from this PR exists in other repositories. These follow-up PRs apply `allowed_classes` restrictions:

| Repo | PR | Status |
|------|-----|--------|
| imp | [#56](https://github.com/horde/imp/pull/56) | Open |
| turba | [#58](https://github.com/horde/turba/pull/58) | Open |
| kronolith | [#47](https://github.com/horde/kronolith/pull/47) | Open |
| nag | [#26](https://github.com/horde/nag/pull/26) | Open |
| mnemo | [#21](https://github.com/horde/mnemo/pull/21) | Open |
| ingo | [#29](https://github.com/horde/ingo/pull/29) | Open |
| Core | [#129](https://github.com/horde/Core/pull/129) | Open |
| base | [#98](https://github.com/horde/base/pull/98) | Open |
| Prefs | [#6](https://github.com/horde/Prefs/pull/6) | Open |

Previously merged related work:
| Repo | PR | Title |
|------|-----|-------|
| Prefs | [#5](https://github.com/horde/Prefs/pull/5) | Harden Horde_Prefs_Identity against unexpected prefs values |
| ActiveSync | [#21](https://github.com/horde/ActiveSync/pull/21) | Modern __serialize()/__unserialize() for Folder classes |
| ActiveSync | [#25](https://github.com/horde/ActiveSync/pull/25) | Refactor unserialize calls to use _unserializeState |

2026-05-27 11:55 UTC, ralflang commented
This branch wasn't possible to merge within the PHP version constraints Horde 5 / master was meant to run on. By now it has inspired a set of other PRs adressing the same or similar issues. Thank you for this contribution even if it didn't work out the way it was intended.

I am formally closing this issue as there is no "implemented differently" workflow.

2026-05-27 11:55 UTC, closed without merging